import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {sourceChain,meshFingerprints,fingerprint,verifySailProvenance} from './sail_provenance.mjs';
const root=new URL('../../',import.meta.url),here=new URL('tools/art/sail-source/',root);
const rootPath=fileURLToPath(root);
const path=p=>new URL(p,root),local=p=>new URL(p,here);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=url=>{const bytes=fs.readFileSync(url),n=bytes.readUInt32LE(12);return {bytes,doc:JSON.parse(bytes.subarray(20,20+n)),bin:bytes.subarray(28+n)};};
const base=read(path('assets/art/sail.glb'));
const rig=read(path('.dream-loop/sail-export/static-rig.glb'));
assert.equal(base.doc.asset.extras.aether_sail_pipeline,undefined,'run build_sail_r52.py before assembly; do not append twice');
assert.equal(base.doc.asset.extras.aether_generator_sha256,hash(fs.readFileSync(path('tools/art/build_sail_r52.py'))),'canvas base must be freshly generated by the current source');
const rigManifest=JSON.parse(fs.readFileSync(local('static-manifest.json')));
assert.equal(rigManifest.rig_glb_sha256,hash(rig.bytes));
assert.equal(rigManifest.generator_sha256,hash(fs.readFileSync(path('tools/art/build_sail_rig.py'))));
assert.equal(rigManifest.helper_sha256,hash(fs.readFileSync(path('tools/art/build_ship.py'))));
const original=structuredClone(base.doc),doc=structuredClone(original);
const aOffset=doc.accessors.length,bOffset=base.bin.length;
const materialMap=rig.doc.materials.map(m=>{const i=doc.materials.findIndex(old=>old.name===m.name);assert.ok(i>=0,`same material ${m.name}`);return i;});
// Static textures reuse the canonical materials. Do not append the temporary
// export's duplicate cedar images to every ship download.
const imageViews=new Set((rig.doc.images??[]).map(i=>i.bufferView));
const viewMap=new Map(),segments=[];let geometryBytes=0;
for(const [i,v] of rig.doc.bufferViews.entries()){
  if(imageViews.has(i))continue;
  const pad=(4-geometryBytes%4)%4;if(pad){segments.push(Buffer.alloc(pad));geometryBytes+=pad;}
  viewMap.set(i,doc.bufferViews.length);doc.bufferViews.push({...v,buffer:0,byteOffset:bOffset+geometryBytes});
  const chunk=rig.bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength);segments.push(chunk);geometryBytes+=chunk.length;
}
doc.accessors.push(...rig.doc.accessors.map(a=>{
  const r=structuredClone(a);if(r.bufferView!==undefined)r.bufferView=viewMap.get(r.bufferView);
  if(r.sparse){r.sparse.indices.bufferView=viewMap.get(r.sparse.indices.bufferView);r.sparse.values.bufferView=viewMap.get(r.sparse.values.bufferView);}return r;
}));
const cloth=doc.meshes.filter(m=>m.primitives.some(p=>p.targets?.length));
doc.meshes=[...cloth,...rig.doc.meshes.map(m=>({...m,primitives:m.primitives.map(p=>({...p,attributes:Object.fromEntries(Object.entries(p.attributes).map(([k,v])=>[k,v+aOffset])),indices:p.indices+aOffset,material:materialMap[p.material]}))}))];
doc.nodes=doc.meshes.map((m,mesh)=>({name:mesh<cloth.length?original.nodes.find(n=>original.meshes[n.mesh]===original.meshes.find(o=>o.name===m.name))?.name??m.name:m.name,mesh}));
doc.scenes=[{name:'Authored voxel sail and naval spars',nodes:doc.nodes.map((_,i)=>i)}];doc.scene=0;
delete doc.asset.extras.aether_generator_sha256;
const padding=(4-geometryBytes%4)%4;segments.push(Buffer.alloc(padding));geometryBytes+=padding;
doc.buffers=[{byteLength:bOffset+geometryBytes}];
const binary=Buffer.concat([base.bin,...segments]);
const clothBefore=meshFingerprints(original,base.bin,true),clothAfter=meshFingerprints(doc,binary,true);
assert.deepEqual(clothAfter,clothBefore,'every resolved cloth accessor and morph must be unchanged');
const pipeline={schema:1,sources:sourceChain(rootPath),input_sail_sha256:hash(base.bytes),input_rig_sha256:hash(rig.bytes),cloth_payload_sha256:fingerprint(clothAfter),static_payload_sha256:fingerprint(meshFingerprints(doc,binary,false))};
doc.asset.extras.aether_sail_pipeline=pipeline;
let text=Buffer.from(JSON.stringify(doc));text=Buffer.concat([text,Buffer.alloc((4-text.length%4)%4,32)]);
const head=Buffer.alloc(20),bhead=Buffer.alloc(8);head.writeUInt32LE(0x46546c67);head.writeUInt32LE(2,4);head.writeUInt32LE(28+text.length+binary.length,8);head.writeUInt32LE(text.length,12);head.writeUInt32LE(0x4e4f534a,16);bhead.writeUInt32LE(binary.length);bhead.writeUInt32LE(0x004e4942,4);
const bytes=Buffer.concat([head,text,bhead,binary]);
for(const m of cloth){
  const old=original.meshes.find(o=>o.name===m.name);assert.deepEqual(m,old);
  assert.deepEqual(m.extras.targetNames,['WindPressure','RippleSin','RippleCos']);
  for(const p of m.primitives){
    assert.equal(p.targets.length,3);
    for(const a of [p.indices,...Object.values(p.attributes),...p.targets.flatMap(t=>Object.values(t))]){
      assert.deepEqual(doc.accessors[a],original.accessors[a]);
      const acc=doc.accessors[a],views=[acc.bufferView,...(acc.sparse?[acc.sparse.indices.bufferView,acc.sparse.values.bufferView]:[])].filter(x=>x!==undefined);
      for(const index of views){const v=doc.bufferViews[index];assert.deepEqual(v,original.bufferViews[index]);assert.ok(binary.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength).equals(base.bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength)));}
    }
  }
}
let minNormal=Infinity,maxNormal=0,badNormals=0,degenerate=0,inwardTriangles=0;
const components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
function accessor(i){const a=doc.accessors[i],v=doc.bufferViews[a.bufferView],count=components[a.type];assert.equal(a.componentType,5126);return Array.from({length:a.count},(_,n)=>Array.from({length:count},(_,k)=>binary.readFloatLE((v.byteOffset??0)+(a.byteOffset??0)+n*(v.byteStride??count*4)+k*4)));}
const newBounds=[[Infinity,-Infinity],[Infinity,-Infinity],[Infinity,-Infinity]];
for(const m of doc.meshes.slice(cloth.length))for(const p of m.primitives){
  assert.equal(p.targets,undefined);assert.ok(p.attributes.TANGENT!==undefined);
  for(const n of accessor(p.attributes.NORMAL)){const length=Math.hypot(...n);minNormal=Math.min(minNormal,length);maxNormal=Math.max(maxNormal,length);if(!Number.isFinite(length)||Math.abs(length-1)>.001)badNormals++;}
  const points=accessor(p.attributes.POSITION),normals=accessor(p.attributes.NORMAL);for(const q of points)for(let j=0;j<3;j++){newBounds[j][0]=Math.min(newBounds[j][0],q[j]);newBounds[j][1]=Math.max(newBounds[j][1],q[j]);}
  const a=doc.accessors[p.indices],v=doc.bufferViews[a.bufferView],width=a.componentType===5125?4:2;
  const get=i=>{const o=(v.byteOffset??0)+(a.byteOffset??0)+i*width;return width===4?binary.readUInt32LE(o):binary.readUInt16LE(o);};
  for(let i=0;i<a.count;i+=3){const ids=[get(i),get(i+1),get(i+2)],[a,b,c]=ids.map(n=>points[n]),u=b.map((n,j)=>n-a[j]),v=c.map((n,j)=>n-a[j]);const cross=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],area=Math.hypot(...cross);if(area<1e-12)degenerate++;const normal=[0,1,2].map(j=>ids.reduce((n,k)=>n+normals[k][j],0));if(cross.reduce((sum,x,j)=>sum+x*normal[j],0)<-1e-10)inwardTriangles++;}
}
assert.equal(badNormals,0);assert.equal(degenerate,0);assert.equal(inwardTriangles,0);
const originalBounds=[0,1,2].map(j=>[Math.min(...original.meshes.flatMap(m=>m.primitives).map(p=>original.accessors[p.attributes.POSITION].min[j])),Math.max(...original.meshes.flatMap(m=>m.primitives).map(p=>original.accessors[p.attributes.POSITION].max[j]))]);
for(let j=0;j<3;j++){assert.ok(newBounds[j][0]>=originalBounds[j][0]-1e-5);assert.ok(newBounds[j][1]<=originalBounds[j][1]+1e-5);}
const triangles=d=>d.meshes.flatMap(m=>m.primitives).reduce((n,p)=>n+d.accessors[p.indices].count/3,0);
const oldCount=triangles(original),newCount=triangles(doc);
const report={pipeline,result_sha256:hash(bytes),before:{sha256:hash(base.bytes),bytes:base.bytes.length,triangles:oldCount,meshes:original.meshes.length},after:{bytes:bytes.length,triangles:newCount,meshes:doc.meshes.length,materials:doc.materials.length},cloth_exact:true,cloth_before:clothBefore,delta_triangles:newCount-oldCount,normals:{min_length:minNormal,max_length:maxNormal,invalid:badNormals,inward_triangles:inwardTriangles},new_degenerate_triangles:degenerate,new_static_bounds_xyz:newBounds,existing_envelope_contained:true};
fs.mkdirSync(local('evidence/'),{recursive:true});
fs.writeFileSync(local('evidence/sail-provenance.json'),JSON.stringify(report,null,2)+'\n');
verifySailProvenance(doc,binary,rootPath,bytes);
// Keep the reproducible pre-assembly input for optional CPU comparison only;
// tracked proof is the compact payload manifest under tools/art/sail-source.
fs.writeFileSync(path('.dream-loop/sail-export/base-sail.glb'),base.bytes);
fs.writeFileSync(path('assets/art/sail.glb'),bytes);
console.log(JSON.stringify({sha256:report.result_sha256,before:report.before,after:report.after,cloth_payload_sha256:pipeline.cloth_payload_sha256,static_payload_sha256:pipeline.static_payload_sha256},null,2));
