[package]
name = "runner"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "runner_exec"
path = "src/main.rs"

[lib]
name = "runner_game"
crate-type = ["rlib", "cdylib"]

[dependencies]
bevy.workspace = true
aether_app.workspace = true
aether_runner.workspace = true
