pub mod app;
pub mod atlas;
pub mod audio;
pub mod bindings;
pub mod camera;
#[cfg(not(target_arch = "wasm32"))]
pub mod closing;
pub mod controls;
pub mod diagnostics;
pub mod editor;
pub mod engineering;
pub mod exploration;
pub mod interface;
pub mod persistence;
pub mod scenario;
pub mod session;
pub mod travel;
pub mod tutorial;

pub use app::run;
