import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
test('voile voxel animée par le vent, pause et reprise sans nouveaux meshes',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const snap=()=>page.evaluate(()=>window.aetherProbe);
 await page.goto('./?probe=1');await expect.poll(async()=>(await snap())?.phase,{timeout:60000}).toBe('Menu');
 await page.keyboard.press('Enter');await expect.poll(async()=>(await snap()).phase).toBe('Playing');
 await expect.poll(async()=>(await snap()).sail_motion?.length).toBeGreaterThanOrEqual(3);
 await expect.poll(async()=>(await snap()).mesh_pending).toBe(0);
 await page.waitForTimeout(600);const first=await snap();
 await page.screenshot({path:'../docs/evidence/sail-wind-a.png'});
 await page.waitForTimeout(1700);const moving=await snap();
 expect(moving.sail_motion[0].weights).not.toEqual(first.sail_motion[0].weights);
 expect(Math.abs(moving.sail_motion[0].speed-first.sail_motion[0].speed)).toBeGreaterThan(.02);
 expect(moving.mesh_assets).toBe(first.mesh_assets);
 expect(moving.sail_motion.every(s=>s.weights.length===3&&s.weights.every(w=>Number.isFinite(w)&&Math.abs(w)<=1))).toBe(true);
 await page.screenshot({path:'../docs/evidence/sail-wind-b.png'});
 await page.keyboard.press('Escape');await expect.poll(async()=>(await snap()).phase).toBe('Paused');await page.waitForTimeout(400);
 const paused=await snap();await page.waitForTimeout(700);expect((await snap()).sail_motion).toEqual(paused.sail_motion);
 await page.keyboard.press('Escape');await expect.poll(async()=>(await snap()).phase).toBe('Playing');
 await page.keyboard.press('Control+s');await expect.poll(async()=>(await snap()).notice).toContain('enregistrée');
 await page.keyboard.press('Control+o');
 await expect.poll(async()=>(await snap()).pending_storage).toBe(false);
 await expect.poll(async()=>(await snap()).mesh_pending).toBe(0);
 await expect.poll(async()=>(await snap()).sail_motion.length).toBe(first.sail_motion.length);
 await expect.poll(async()=>(await snap()).mesh_assets).toBe(first.mesh_assets);
 expect(errors).toEqual([]);
 await fs.writeFile('../docs/evidence/sail-wind.json',JSON.stringify({first:first.sail_motion,moving:moving.sail_motion,paused:paused.sail_motion,surfaces:first.sail_motion.length,meshes:first.mesh_assets,errors},null,2));
});
